AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/ClassAndModuleChildren:
  Enabled: false

Bundler/DuplicatedGroup:
  Enabled: true

Style/MutableConstant:
  Enabled: false

Layout/SpaceInsideArrayLiteralBrackets:
  EnforcedStyle: no_space
