name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  scan_ruby:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
      - name: Scan for common Rails security vulnerabilities using static analysis
        run: bin/brakeman --no-pager

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
      - name: Lint code for consistent style
        run: bin/rubocop -f github

  verify_project_setup:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
      - name: Verify project setup
        env:
          RAILS_ENV: test
          DATABASE_URL: mysql2://root:@127.0.0.1:3306
        run: |
          bin/rails db:create
          bin/rails db:schema:load
          echo "Running Rails console to verify environment..."
          bin/rails runner "puts 'Rails environment is set up correctly'"
      - name: Check for test files
        run: |
          test_files=$(find test -name '*_test.rb')
          if [ -z "$test_files" ]; then
            echo "Warning: No test files found. Consider adding tests to your project."
          else
            echo "Test files found:"
            echo "$test_files"
          fi
